### ISSUE TITLE
Bug with custom post type slug

### ISSUE THREAD

**Issue by nikolailehbrink** [amarinediary/Where-Is-My-Bread#11]
Hi there again. I just noticed something strange. I registered a custom post type with:

```
'rewrite' => array(
	'slug' => 'team',
	'with_front' => false
)
```

When I open the /team site the breadcrumb only shows the first homepage as a link of "Start" instead of "Start  → Team".
I set the start node with:
```
<?php
    $ingredients = array(
        'separator' => '→',
        'root' => array(
            'slug' => 'Start',
            'url' => get_home_url(),
        ),
    );
    the_bread($ingredients);
?>
```

In all other cases, when no cpt is registered with a slug, it works fine.

**Comment by amarinediary** [comment]
Indeed, I see what you mean... The initial idea was to filter out taxonomies and post types because WordPress doesn't generate an index for them, meaning, that `mywebsite.com/taxonomy` would redirect to a `404.php`.
Same goes for post types, except if you're using an archive page. As I wasn't using one at the time of the initial development I didn't noticed the issue.
The fix is pretty straight forward, I will remove the post type filtering and push the new update `1.2.2` during the day.

**Comment by amarinediary** [comment]
### [Current plugin version: `1.2.2`](https://github.com/amarinediary/WordPress-simple-URL-based-breadcrumb/releases/tag/1.2.2)

#### `1.2.2`
- [x] Custom post types crumbs are now being displayed correctly.
- [x] You can now intercept the crumbs array. See [Example: Intercepting the crumbs array](https://github.com/amarinediary/WordPress-simple-URL-based-breadcrumb#example-intercepting-the-crumbs-array).
- [x] Code commenting improvements.
- [x] Emphasis on [WordPress coding standards](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/). 
- [x] [README.md](https://github.com/amarinediary/WordPress-simple-URL-based-breadcrumb/blob/main/README.md) updates.
- Special thanks to [@nikolailehbrink](https://github.com/nikolailehbrink) for the feedback.
